name: "Build kernel."
on:
  push:
    branches: darky
  workflow_dispatch:
jobs:
  build:
    name: "Build kernel"
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout kernel source".
      uses: actions/checkout@v2
    - name: "Checkout zipper"
      uses: actions/checkout@v2
      with:
        repository: lemniskett/AnyKernel3             # Your own AnyKernel3 repository.
        path: zipper                                  # Clone to path "zipper", REQUIRED.
    - name: "Android kernel build"                    # Build kernel with lemniskett/android-kernel-actions.
      uses: lemniskett/android-kernel-actions@master
      with:
        arch: arm64                                   # Specify arch
        compiler: gcc/9                               # Specify toolchain to use
